### ISSUE TITLE
MODULE_NOT_FOUND when depending on only one facade

### ISSUE THREAD

**Issue by moh-sen** [exoego/aws-sdk-scalajs-facade#211]
Hi,

I use only `aws-sdk-scalajs-facade-dynamodb` in my project by adding the following to the build.sbt:

`libraryDependencies += "net.exoego" %%% "aws-sdk-scalajs-facade-dynamodb" % "0.29.0-v2.624.0"`

When I run my project I get the following error:

[error] facade.amazonaws.services.dynamodb.DynamoDB needs to be imported from module 'aws-sdk' but module support is disabled.
[error] There were module imports without fallback to global variables, but module support is disabled.
[error] To enable module support, set `scalaJSLinkerConfig ~= (_.withModuleKind(ModuleKind.CommonJSModule))`.

When I add `scalaJSLinkerConfig ~= (_.withModuleKind(ModuleKind.CommonJSModule))` as suggested, the previous error is gone but there is a new one as follows:

`Error: Cannot find module 'aws-sdk'`

Do I still miss something?

Thank you!

**Comment by exoego** [comment]
Thanks for reporting 👍 

The two errors happen because this facade requires that the peer JS dependency [`aws-sdk`](https://github.com/aws/aws-sdk-js) must be available on runtime.
I think "Getting Started" of this repository should mention that, so I added it in PR #212.

It would be thankful if you try this addition and check the errors resolved (or not).

**Comment by moh-sen** [comment]
Thanks for your quick reply.

Yes this in fact fixes the error. Great that you updated the documentation.

**Comment by exoego** [comment]
Great, thanks.
The document now updated.
Let me close as resolved.
